SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
DROP DATABASE IF EXISTS EASYGAME_SMARTFARM;
CREATE DATABASE EASYGAME_SMARTFARM;
USE EASYGAME_SMARTFARM;

CREATE TABLE USER (
    UserID INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    fname VARCHAR(255) DEFAULT NULL,
    lname VARCHAR(255) DEFAULT NULL,
    gender BOOLEAN DEFAULT NULL,
    phone_number VARCHAR(10) DEFAULT NULL,
    `password` VARCHAR(255) NOT NULL,
    PRIMARY KEY (UserID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CONTROL (
  `Manual_mode` bit(1) not null,
  `Den1` bit(1) NOT NULL,
  `Bom1` bit(1) NOT NULL,
  `Ps1` bit(1) NOT NULL,
  `Rc1` bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO CONTROL VALUES (0,0,0,0,0);

CREATE TABLE AUTO (
  `Temperature` int(11) NOT NULL,
  `Humidity` int(11) NOT NULL,
  `Light` int(11) NOT NULL,
  `Mois` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO AUTO VALUES (25, 95, 200, 80);



CREATE TABLE GARDEN (
    GardenID INT NOT NULL AUTO_INCREMENT,
    Vi_tri VARCHAR(255) DEFAULT NULL,
    So_cay INT DEFAULT NULL,
    Che_do_quan_ly VARCHAR(255) DEFAULT NULL,
    Tinh_trang VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (GardenID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO GARDEN VALUES (1, "Thu Duc, Ho Chi Minh City", 10, NULL, NULL);


CREATE TABLE DEVICE (
    DeviceID INT NOT NULL AUTO_INCREMENT,
    GardenID INT NOT NULL,
    Ten VARCHAR(255) DEFAULT NULL,
    Tinh_trang VARCHAR(255) DEFAULT NULL,
    Trang_thai BOOLEAN DEFAULT NULL,
    Cong_dung VARCHAR(255) DEFAULT NULL,
    Mo_ta VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (DeviceID, GardenID),
    FOREIGN KEY (GardenID) REFERENCES GARDEN(GardenID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO DEVICE VALUES (1, 1, "TEMP_01", null, null, "Do nhiet do garden 1", null);
INSERT INTO DEVICE VALUES (2, 1, "MOIS_01", null, null, "Do do am dat garden 1", null);
INSERT INTO DEVICE VALUES (3, 1, "HUMID_01", null, null, "Do do am khong khi garden 1", null);
INSERT INTO DEVICE VALUES (4, 1, "LIGHT_01", null, null, "Do cuong do anh sang garden 1", null);

CREATE TABLE T_TEMPERATURE (
  `id` int(11) NOT NULL,
  `value` int(11) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO T_TEMPERATURE VALUES
(0, 30, '2023-04-03 08:53:27'),
(1, 30, '2023-04-03 08:53:32');

CREATE TABLE T_MOISTURE (
  `id` int(11) NOT NULL,
  `value` int(11) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO T_MOISTURE VALUES (0, 30, '2023-04-03 08:53:27'), (1, 30, '2023-04-03 08:53:32');

CREATE TABLE T_LIGHT (
  `id` int(11) NOT NULL,
  `value` int(11) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO T_LIGHT (`id`, `value`, `date`) VALUES
(0, 30, '2023-01-03 08:53:27'),
(1, 30, '2023-01-03 08:53:27');


CREATE TABLE T_HUMID (
  `id` int(11) NOT NULL,
  `value` int(11) NOT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO T_HUMID VALUES (0, 30, '2023-04-03 08:53:27'), (1, 30, '2023-04-03 08:53:32');


CREATE TABLE STATUS (
  Trang_thai_den int(11) NOT NULL,
   Trang_thai_phunsuong int(11) NOT NULL,
  Trang_thai_maybom int(11) NOT NULL,
  Trang_thai_RC int(11) NOT NULL
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DISPLAY (
  `Temperature` int(11) NOT NULL,
  `Humidity` int(11) NOT NULL,
  `Light` int(11) NOT NULL,
  `Mois` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO DISPLAY VALUES (30, 90, 1000, 100);


INSERT INTO STATUS VALUES (0,0,0,0);

INSERT INTO USER (email, `password`) VALUES
('admin@gmail.com', 'admin');
COMMIT;