DROP DATABASE IF EXISTS EASYGAME_SMARTFARM;

CREATE DATABASE EASYGAME_SMARTFARM;
USE EASYGAME_SMARTFARM;

CREATE TABLE USER (
    UserID INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    fname VARCHAR(255) DEFAULT NULL,
    lname VARCHAR(255) DEFAULT NULL,
    gender BOOLEAN DEFAULT NULL,
    phone_number VARCHAR(10) DEFAULT NULL,
    _password VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (UserID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE GARDEN (
    GardenID INT NOT NULL AUTO_INCREMENT,
    Vi_tri VARCHAR(255) DEFAULT NULL,
    So_cay INT DEFAULT NULL,
    Che_do_quan_ly VARCHAR(255) DEFAULT NULL,
    Tinh_trang VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (GardenID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE DEVICE (
    DeviceID INT NOT NULL AUTO_INCREMENT,
    GardenID INT NOT NULL,
    Ten VARCHAR(255) DEFAULT NULL,
    Tinh_trang VARCHAR(255) DEFAULT NULL,
    Trang_thai BOOLEAN DEFAULT NULL,
    Thong_so_do_duoc INT DEFAULT NULL,
    Cong_dung VARCHAR(255) DEFAULT NULL,
    Mo_ta VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (DeviceID),
    FOREIGN KEY (GardenID) REFERENCES GARDEN(GardenID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PLANT (
    PlantID INT NOT NULL AUTO_INCREMENT,
    GardenID INT NOT NULL,
    Ten VARCHAR(255) DEFAULT NULL,
    Tinh_trang VARCHAR(255) DEFAULT NULL,
    So_luong INT DEFAULT NULL,
    Muc_phat_trien VARCHAR(255) DEFAULT NULL,
    Ngay_trong DATE DEFAULT NULL,
    Ghi_chu VARCHAR(255) DEFAULT NULL,
    def_Cuong_do_anh_sang FLOAT DEFAULT NULL,
    def_Nhiet_do FLOAT DEFAULT NULL,
    def_Do_am_dat FLOAT DEFAULT NULL,
    def_Do_am_khong_khi FLOAT DEFAULT NULL,
    PRIMARY KEY (PlantID),
    FOREIGN KEY (GardenID) REFERENCES GARDEN(GardenID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into USER(email, _password) values ('admin', '*23AE809DDACAF96AF0FD78ED04B6A265E05AA257')